### ISSUE TITLE
How to disable Redis TLS even if TLS Port properties available from Cloud Foundry?

### ISSUE THREAD

**Issue by joaodias14** [pivotal-cf/java-cfenv#142]
Currently we get from our Cloud Foundry platform the Redis TLS Port property, this means that `RedisCfEnvProcessor.java` will set "spring.redis.ssl" property to true. The issue is that we want to disable this because of its huge performance penalty but we can't remove TLS Port from Cloud Foundry environment variables.
How can we achieve this?

**Comment by scottfrederick** [comment]
@joaodias14 Java CFEnv sets Boot properties in a property source. Any properties like `spring.redis.ssl` can be overridden in another property source that has higher precedence.

**Comment by pivotal-david-osullivan** [comment]
Hi @joaodias14, revisiting this issue, has @scottfrederick's suggestion to use a source with higher precedence helped with your case?

**Comment by pivotal-david-osullivan** [comment]
Closing this out for now, workaround shared
