### ISSUE TITLE
3.0.0 Snapshot looks like it has a bug configuring SSL when using PCF Redis service tile

### ISSUE THREAD

**Issue by ahall-vmware** [pivotal-cf/java-cfenv#218]
The [documentation for SSL enabling](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.nosql.redis.connecting) uses the property `spring.data.redis.ssl.enabled`, whereas the `RedisCfEnvProcessor` is using `.ssl` without the `.enabled` piece.

https://github.com/pivotal-cf/java-cfenv/blob/a28f4573079fb58a8c897077ce9ac30623827da6/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessor.java#L61

and

https://github.com/pivotal-cf/java-cfenv/blob/a28f4573079fb58a8c897077ce9ac30623827da6/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessor.java#L71
This results in errors like:

```
Update your application's configuration 
Action:
Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.data.redis.RedisProperties$Ssl]

Failed to bind properties under 'spring.data.redis.ssl' to org.springframework.boot.autoconfigure.data.redis.RedisProperties$Ssl:
```

**Comment by ilker-yapikredi** [comment]
Hi, any progress on this? I had the same issue.

**Comment by anthonydahanne** [comment]
hello! 
it's fixed with https://github.com/pivotal-cf/java-cfenv/pull/254 and in release 3.2.0 , https://github.com/pivotal-cf/java-cfenv/releases/tag/v3.2.0
