### ISSUE TITLE
Configure cfenv.service.<serviceName>.enabled=false in application.yaml

### ISSUE THREAD

**Issue by Marty850** [pivotal-cf/java-cfenv#231]
### Is your feature request related to a problem? Please describe.

We noticed that java-cfenv changes special characters in the password of our jdbc connectionString. Thats why we would like to disable cfenv for that service.

We found the parameter `cfenv.service.<serviceName>.enabled=false` that is documented [here](https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections.html) but it is not possible to configure at in a yaml file. Only application.properties works.

### Describe the solution you'd like

I would like to have the possibility to disable java-cfenv for a service by using both configuration methods (application.yaml and application.properties)

**Comment by Marty850** [comment]
I just noticed that it is possible to configure it in application.yaml as well by putting it in the first line and change the = to a : 

`cfenv.service.<serviceName>.enabled: false`

Maybe it's enough to add a hint to the documentation.

**Comment by anthonydahanne** [comment]
Hello!
>We noticed that java-cfenv changes special characters in the password of our jdbc connectionString.

Just to be sure, it was happening with a `DB2` connection string?

> Maybe it's enough to add a hint to the documentation.

Yes, that makes sense

**Comment by Marty850** [comment]
Hi Anthony,
yes it is a DB2 connection string. 

cf-env does a url encoding and the db2 driver cannot deal with that. So cf-env is currently not usable for db2 connections unless you use `cfenv.service.<serviceName>.enabled=false` as a workaround.

**Comment by Marty850** [comment]
I noticed your Fix for the URL encoding issue. Can you say when this will be released?

**Comment by anthonydahanne** [comment]
today! `3.1.3` is available on central!

https://github.com/pivotal-cf/java-cfenv/releases/tag/v3.1.3
