### ISSUE TITLE
fix for update to json-io 4.19.2+

### ISSUE THREAD

**Issue by mohadipe** [pivotal-cf/java-cfenv#260]
### Is your feature request related to a problem? Please describe.

If you use com.cedarsoftware:json-io in a version from 4.19.2+ and also use java-cfenv, this is no longer a compatible combination. This is because the package in json-io has changed from `com.cedarsoftware.util.io.JsonObject` to `com.cedarsoftware.io.JsonObject`.

### Describe the solution you'd like

I have developed a possible solution for this situation. 

[update_json-io_to_4_19_10__-_fix_incompatible_change__package_for_JsonObject_has_changed.patch](https://github.com/pivotal-cf/java-cfenv/files/14720238/update_json-io_to_4_19_10__-_fix_incompatible_change__package_for_JsonObject_has_changed.patch)

I would be pleased if this correction were included. So that I can use new versions of json-io.

**Comment by jsnyder4** [comment]
While you won't be able to change the version of json-io that `java-cfenv` is using, you can use json-io 4.19.11. The packing as been changed so that nothing interferes with the old packaging that `java-cfenv` is using.

That being said, the devs of `java-cfenv` are trying to use a gradle plugin that shades/relocates json-io to another package for the cfenv usage. However, that plugin doesn't seem to work properly.
You can see the plugin usage [here](https://github.com/pivotal-cf/java-cfenv/blob/713fe11955597ca6a809700f8d5a6ea0e48f45b3/java-cfenv-all/build.gradle#L39).

**Comment by mohadipe** [comment]
> While you won't be able to change the version of json-io that java-cfenv is using, you can use json-io 4.19.11. The packing as been changed so that nothing interferes with the old packaging that java-cfenv is using.

I do not understand your suggestion because json-io 4.19.11 is still incompatible with java-cfenv-boot 3.1.5. The class JsonObject is not found at runtime.

> That being said, the devs of java-cfenv are trying to use a gradle plugin that shades/relocates json-io to another package for the cfenv usage. However, that plugin doesn't seem to work properly.
> You can see the plugin usage [here](https://github.com/pivotal-cf/java-cfenv/blob/713fe11955597ca6a809700f8d5a6ea0e48f45b3/java-cfenv-all/build.gradle#L39).

Why did you try to relocate the package instead of fixing the imports?

**Comment by jsnyder4** [comment]
I'm not a java-cfenv author, just a guy familiar with the problem and trying to help you out.

**Comment by mohadipe** [comment]
Thank you for your help. 

> Why did you try to relocate the package instead of fixing the imports?

I thought you might know that

**Comment by n-shaw** [comment]
@mohadipe, please take a look at [issue#261](https://github.com/pivotal-cf/java-cfenv/issues/261).  That is what caused problems for you and other [json-io](https://github.com/jdereg/json-io) users.  I believe the reason json-io shifted the package was specifically to address the issue with java-cfenv not shading the complete json-io namespace. 

Once issue#261 is fixed, this enhancement is unnecessary.

**Comment by anthonydahanne** [comment]
Hello !
Can we close this issue? I believe all is well now between java-cfenv shading and json-io since this [commit](https://github.com/pivotal-cf/java-cfenv/commit/c4cae06087a8aadd1b65d58f77050cf6aed023ce) got merged in?
Thanks!
