### ISSUE TITLE
com.cedarsoftware:json-io is not completely shaded

### ISSUE THREAD

**Issue by n-shaw** [pivotal-cf/java-cfenv#261]
### Describe the bug

The shadowJar task in the `java-cfenv-all` [build.gradle](https://github.com/pivotal-cf/java-cfenv/blob/main/java-cfenv-all/build.gradle) is relocating with a package name that is too specific.  This can cause issues with customers who depend on json-io in their projects (directly or indirectly/transitively) when their apps are deployed/packaged with the buildpack uberjar.

Instead of `com.cedarsoftware.util.io`, it should simply be `com.cedarsoftware`.  Otherwise, there will be about 20 `json-io` classes left in the original package, while the rest move under `io.pivotal.cfenv.shaded.com.cedarsoftware.util.io`.

```gradle
shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
    transform(PropertiesFileTransformer) {
        paths = ['META-INF/spring.factories']
        mergeStrategy = "append"
    }
    dependencies {
        exclude(dependency('org.springframework.boot::'))
        exclude(dependency('org.springframework::'))
    }
    relocate 'com.cedarsoftware.util.io', 'io.pivotal.cfenv.shaded.com.cedarsoftware.util.io'
}
```

The `relocate` step should say: 
```gradle
    relocate 'com.cedarsoftware', 'io.pivotal.cfenv.shaded.com.cedarsoftware'
```

### Reproduction steps

1. Download the [java-cfenv uber jar](https://java-buildpack.cloudfoundry.org/java-cfenv/java-cfenv-3.1.5.jar).
2. Extract the contents: `jar -xvf java-cfenv-3.1.5.jar
3. Browse the folder structure.  
<img width="546" alt="json-io_shadow_split" src="https://github.com/pivotal-cf/java-cfenv/assets/62348053/8cf5200a-1cab-414e-b1bf-04a3a5fd8bf7">

### Expected behavior

All of the classes from` json-io` should be in the `io.pivotal.cfenv.shaded.com.cedarsoftware` namespace.

**Comment by n-shaw** [comment]
@anthonydahanne - Since it can take time for changes to get released, consumed, and then brought in to each customer's environment, I was hoping you could take a look at this issue at your earliest convenience.   Thank you for your consideration.

**Comment by anthonydahanne** [comment]
Hello !
Can we close this issue? I believe all is well now between java-cfenv shading and json-io since this [commit](https://github.com/pivotal-cf/java-cfenv/commit/c4cae06087a8aadd1b65d58f77050cf6aed023ce) got merged in?
Thanks!

**Comment by n-shaw** [comment]
Thanks, @anthonydahanne.
