### ISSUE TITLE
Add isEnabled method to CfEnvProcessor to allow for each implementation to be turned off via an environment variable.

### ISSUE THREAD

**Issue by markpollack** [pivotal-cf/java-cfenv#28]

**Comment by markpollack** [comment]
This helps to opt out of a specific service when there is more than one service of the same type bound to the application.

**Comment by dturanski** [comment]
@markpollack Question re `CfDataSourceEnvironmentPostProcessor`.  Currently not a `CfEnvProcessor`. Is that the intention?  If so, it adds some slight complexity to this.
