### ISSUE TITLE
Undocumented 3.3.0 Release

### ISSUE THREAD

**Issue by Alfagun74** [pivotal-cf/java-cfenv#284]
My Renovate bot recently found an upgrade to version 3.3.0 for `java-cfenv-boot`, which is causing issues when I deploy my app to Cloud Foundry.

Link: [java-cfenv-boot 3.3.0 on Maven](https://mvnrepository.com/artifact/io.pivotal.cfenv/java-cfenv-boot/3.3.0)

However, I checked the repository and noticed that version 3.3.0 doesn’t appear in the codebase or the releases tab. 

Could this be a potential supply chain security issue?

**Comment by Alfagun74** [comment]
possibly related to https://github.com/pivotal-cf/java-cfenv/pull/282

**Comment by anthonydahanne** [comment]
hello!
yeah sorry, I just forgot to create a release from the tag.
You can check it out there: https://github.com/pivotal-cf/java-cfenv/releases/tag/v3.3.0

Please open a new one in case you found a new issue with this release!
Thanks!
