### ISSUE TITLE
Add spring-cloud-config-client runtime dependency

### ISSUE THREAD

**Issue by dturanski** [pivotal-cf/java-cfenv#41]
add dependency to  java-cfenv-boot-pivotal-scs see https://docs.pivotal.io/spring-cloud-services/2-0/common/client-dependencies.html

**Comment by markpollack** [comment]
I believe this was added for the 1.0.1.RELEASE - https://github.com/pivotal-cf/java-cfenv/commit/918926cd5f41d6aa13e70141e7a5ebd9b1471b95
