### ISSUE TITLE
Add LICENSE file to enable reuse in other projects

### ISSUE THREAD

**Issue by sebastianbuchholz** [pivotal-cf/java-cfenv#45]
Hi,
we would love to use your library for creating Spring Beans in our cloud-foundry-project.

However due to organisational constraints we are only allowed to use open source projects under certain license agreements.

As your project appears to be missing a LICENSE file we are unable to determine your license agreement and thus unable to use your project.

 Can you add a LICENSE file to your project so we assess if we can make use of your Project?

**Comment by markpollack** [comment]
Added, thanks.  38fd5b7ffbef9274bf3a0d3c40cb5e5c23990aa0
