### ISSUE TITLE
Rabbitmq ssl properties not matching the one injected by AmqpCfEnvProcessor

### ISSUE THREAD

**Issue by dohantaur** [pivotal-cf/java-cfenv#46]
The injected rabbitmq ssl property is not matching the actual spring boot rabbitmq ssl one. 
If ssl is enabled on RabbitMQ, `AmqpCfEnvProcessor` set the property `spring.rabbitmq.ssl` to `"true"` instead of `spring.rabbitmq.ssl.enabled `.

This cause an error if we do not explicitly set `spring.rabbitmq.ssl.enabled` to `true`.

**Comment by markpollack** [comment]
Much appreciated.  Fixed in b9e32c4169cc095b4e45cefda7b26e55ff87642a
