### ISSUE TITLE
Add support for Spring Security 5 OAuth 2.0 Login

### ISSUE THREAD

**Issue by jgrandja** [pivotal-cf/java-cfenv#48]
Spring Security 5.0 introduced support for [OpenID Connect 1.0](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth) via the [OAuth 2.0 Login](https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#oauth2login) feature. It would be great if we could provide an integration between Spring Security 5 OAuth 2.0 Login and PCF SSO service.

The current implementation of `CfSingleSignOnProcessor` integrates with the legacy [Spring Security OAuth](https://spring.io/projects/spring-security-oauth) project. A new implementation of `CfEnvProcessor` would be very similar to this existing implementation. 

I've put together a sample in this [branch](https://github.com/jgrandja/oauth2login-demo/tree/java-cfenv-pcf-sso) that demonstrates a working integration via [OAuth2LoginSsoServiceCfEnvProcessor](https://github.com/jgrandja/oauth2login-demo/blob/java-cfenv-pcf-sso/src/main/java/io/pivotal/cfenv/boot/sso/oauth2/client/OAuth2LoginSsoServiceCfEnvProcessor.java).

My plan is to submit a PR for this new integration but I'm quite busy targeting for the upcoming release of Spring Security 5.2. Feel free to copy/modify the existing implementation and integrate into master if you have some spare cycles in the coming weeks. I likely won't get to this for another month or so.

/cc @rwinch @asaikali

**Comment by jgrandja** [comment]
Hey @ghillert, can you provide me some background on why `CfSingleSignOnProcessor` is not using the latest Spring Security 5 OAuth 2.0 Client properties? I was chatting with @markpollack and he mentioned that you did the initial scoping and there were some features needed that were missing. I'd like to understand so we can get these features in so you can use the new OAuth 2.0 client support.

**Comment by scottfrederick** [comment]
@jgrandja The Pivotal SSO team has added support for mapping to Spring Security 5 OAuth2 properties (fbdbb66b2586fa5cdc2fe199507713ba245b18ab). Does that cover everything you are suggesting here?

**Comment by jgrandja** [comment]
@scottfrederick I did a quick review and looks like all the properties are being added. However, I noticed that the `scope` property is not being set. I'm wondering if it's required -> `"openid, profile, email"`? Maybe not for UAA.

Either way, as long as it works and it's well tested than looks good.

**Comment by scottfrederick** [comment]
@cameronmoreau See Joe's comment above.

**Comment by willsu** [comment]
Hello @scottfrederick . Thanks for notifying us regarding this issue. 

@jgrandja: we decided to opt out of setting any non-VCAP properties in our new processor. We are in the (late stage) process of updating our Sample Apps with examples and instructions to inform the client that they'll need to set the Spring Security properties for Grant Type and Scope on their own:
https://github.com/pivotal-cf/identity-sample-apps/blob/spring-boot-2.1/authcode/manifest.yml#L17-L21

If you feel strongly that we should provide a convenience mapping for more semantic (i.e. less Spring Security 5 specific) properties for Scope and Grant Type, then we can certainly talk about it. Thanks for looking it over!

**Comment by rwinch** [comment]
I think it makes sense that this project only sets VCAP specific properties. The other properties should just use the standard Spring Security properties.

**Comment by jgrandja** [comment]
@willsu 

> ...the client that they'll need to set the Spring Security properties for Grant Type and Scope on their own

Why does the user need to set this? Why cannot the processor default to:

```
authorization-grant-type: authorization_code
scope: openid,profile,email
```

**NOTE:** `authorization_code` is the only grant-type supported by `oauth2Login()` so there are no other options available to set. And `openid` is a [required scope](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) for OpenID Connect - but maybe UAA doesn't need it?

**Comment by rwinch** [comment]
@jgrandja Don't we default the scopes to the scopes returned by the openid configuration endpoint?

**Comment by jgrandja** [comment]
@rwinch UAA returns the following scopes from the OpenID Discovery Endpoint:

```yaml
"scopes_supported": [
"openid",
"profile",
"email",
"phone",
"roles",
"user_attributes"
],
```

I know I had issues with one of my sample apps with the custom scopes `roles` and `user_attributes` so I had to override the scopes in my local configuration.

We should make sure that the behaviour works as expected if we decide to default the scopes from the OpenID Discovery Endpoint.

**Comment by asaikali** [comment]
I think the SpringBoot philosophy of auto configuration with reasonable defaults that I can easily override is important here.  As an end user the workflow I expect is to bind a service and it just works, so I am all for picking a safe reasonable set of scopes to ask for.

**Comment by rwinch** [comment]
I think we should rely on the supported scopes returned by the discovery endpoint. Alternatively, UAA could provide info in VCAP_SERVICES or add a Spring Environment entry. What we don't want is to tie this project to UAA.

**Comment by asaikali** [comment]
I agree that using the discovery endpoint is the best approach. I have tried that in the past and gotten errors from spring security not sure where the issue was spring security or UAA. Hopefully these issues are fixed and the UAA discovery end point can be used with spring security. 

@rwinch What do you mean by this in the your comment "What we don't want is to tie this project to UAA." what does this refer to spring security or java-cfenv project?

**Comment by rwinch** [comment]
I meant java-cfenv, but neither should be tied to UAA. 

I'd be curious what the issues were when using the supported scopes with the UAA. It seems like that should work, but hard to know without knowing the issues.

**Comment by aramprice** [comment]
looping in some UAA folks for context: @andrewedstrom @dbeneke @wc22222

**Comment by peterhaochen47** [comment]
@jgrandja et al., please correct me if I'm wrong. Here's a summary of my understanding:

(1) **spring security 5** is currently defaulting `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` to the `scopes_supported` value returned by IDP's OpenID Discovery Endpoint. Here's a sample of what that UAA's OpenID Discovery Endpoint looks like for the `scopes_supported` value :
```
"scopes_supported":["openid","profile","email","phone","roles","user_attributes"]
```

(2) If a dev using **spring security 5** in their app sets `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` themselves, e.g., to `foobar`, then the default behavior in (1) will be overridden. Namely,  `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` will be set to `foobar` only and will not include any of the `scopes_supported` such as `"openid","profile"`.

(3) We are now discussing whether `CfSingleSignOnProcessor` should somehow set `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` for the dev? If so, how should that value be set? 

Could you respond to (1), (2), (3) individually?

--- PCF App SSO team.

**Comment by markpollack** [comment]
fixed in fbdbb66b2586fa5cdc2fe199507713ba245b18ab

**Comment by markpollack** [comment]
seems like there is still some open discussion on the feature.

**Comment by jgrandja** [comment]
@peterhaochen47 Regarding Point 2, if the user specifies the `scope` property to `foobar` than OpenID Connect authentication will not be initiated since `openid` is a required scope for OIDC. Given that this feature is all about SSO, the `openid` scope must be set and never overridden. Please review the [OpenID Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

**Comment by peterhaochen47** [comment]
@jgrandja, Yes, I understand that `openid` must be included as part of `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` for AuthN to work. 

The current implementation requires users to include `openid` while setting `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE` for their application on their own, alongside another other scopes they might want to include (see our [current sample apps](https://github.com/pivotal-cf/identity-sample-apps)). Our sample apps, our docs, OIDC specs all instruct users to do that. 

What is your concern?

**Comment by jgrandja** [comment]
@peterhaochen47 I guess it wasn't clear to me when I read this [comment](https://github.com/pivotal-cf/java-cfenv/issues/48#issuecomment-494892034) and Point 2:

> Namely, SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE will be set to **foobar only** and will not include any of the scopes_supported such as "openid","profile"

Based on that scenario, `openid` would not be included in the `scope`.

Anyway, as you stated in your last comment

> The current implementation requires users to include `openid`...

No concern than.

**Comment by peterhaochen47** [comment]
@jgrandja Yeah sorry my point 2 was conditioned on `If a dev using spring security 5 (not CfSingleSignOnProcessor) in their app sets SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE themselves` and was more of a fact gathering comment than describing the desired behavior. 
Thanks for reviewing the code!
