### ISSUE TITLE
Add support for TLS connections from Pivotal Redis service

### ISSUE THREAD

**Issue by scottfrederick** [pivotal-cf/java-cfenv#54]
The PCF Redis Tile team is adding optional TLS support to their Redis offering via stunnel on a separate port from the standard Redis port. In order to avoid breaking existing (non-TLS) customer bindings, this will be exposed via a second port in the service bindings, `tls_port`. If the `tls_port` is exposed in the binding, then TLS support is enabled and can be used for the Redis connection.

**Comment by markpollack** [comment]
fixed in c0f39d7a2e900cc37b900308d88b94725332235e
