### ISSUE TITLE
Provide a cloud agnostic API and extensibility

### ISSUE THREAD

**Issue by csabakos** [pivotal-cf/java-cfenv#64]
`java-cfenv` is the successor of [Spring Cloud Connectors](https://cloud.spring.io/spring-cloud-connectors/) however it is entirely Could Foundry specific and lacks abstractions that are present in Spring Cloud Connectors (such as `CloudFactory` and `AbstractCloudConfig`).

I believe that such abstractions are highly useful as they allow porting applications from one cloud to an other with minimal changes and easy deployment in hybrid clouds.

Please see https://github.com/spring-cloud/spring-cloud-connectors/pull/295 for some relevant discussion.

---

**Example use case:** My company uses a private cloud. We would like to create a custom Cloud Connector (in the Spring Cloud Connectors terminology) that can discover services bound to the application in our private cloud. If somebody then wants to deploy the application onto a public cloud (such as Cloud Foundry) this would make the migration as easy as replacing our custom cloud connector with the Cloud Foundry one (assuming that the bound service names remain unchanged).

Our private cloud injects properties into the Spring configuration. For example, for MySQL, the following properties are injected:
```
mysql.<dbname>.host=
mysql.<dbname>.user=
mysql.<dbname>.password=
mysql.<dbname>.db=
```

We have similar properties for other technologies (Mongo, etc.). The service type is inferred from the property name.

These properties are enumerable via [EnumerablePropertySource](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/env/EnumerablePropertySource.html).

**Comment by markpollack** [comment]
Indeed, java-cfenv, isn't a 1-to-1 replacement for the connector libraries.  I personally don't want to reintroduce those concepts into this library as it is intended to be CF specific.  I know some users of the connector library made use of that abstraction, but I believe it was a very small percentage.

**Comment by markpollack** [comment]
If you need to use https://spring.io/projects/spring-cloud-config  then when using java-cfenv you need to bring in the dependency on 

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency
```

to your application.  The connector library would bring in that as a dependency, but this library does not.

**Comment by csabakos** [comment]
@markpollack What is the recommendation for the users who _were_ using the abstractions in Cloud Connector? Are we supposed to create `java-??env` libraries for every cloud environment?

**Comment by bthelen** [comment]
@csabakos I talked to @markpollack last week about this, and he suggested that yes you would be best served creating an environment parser to meet your platform's conventions.
