### ISSUE TITLE
Consider using a lighter weight JSON parser

### ISSUE THREAD

**Issue by dsyer** [pivotal-cf/java-cfenv#65]
Jackson is fine for some people, but not all apps would need it, so bringing it in as a dependency in this tiny jar seems unfortunate. I see from #12 that we have been through a few cycles of this. Maybe the tiny (vaadin branded?) json parser that Spring Boot used to use could be shaded in (it's only 10K I think)?

**Comment by dsyer** [comment]
Link from Spring Boot: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/json-shade

**Comment by markpollack** [comment]
I had looked around at the time at alternatives and asked a few folks for opinions, using jackson simply felt like a safe choice since the original connector library used it and no one complained.

**Comment by markpollack** [comment]
I'll assign this to a 1.2 M1 for further consideration, I'm fine with such a change fwiw.

**Comment by anthonydahanne** [comment]
@dsyer : your wish came true recently in the latest 3 version of `java-cfenv` ; https://github.com/pivotal-cf/java-cfenv/pull/222/files#diff-3246c132b2de61117694bcb98cab0fcc7f3f4bf27defe029227fb63cb3327e51R9
