### ISSUE TITLE
AmqpCfEnvProcessor configures port to 5672 instead of 5671 when ssl enabled 

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/java-cfenv#74]
Enabled SSL on a RabbitMQ service instance and noticed the port was still 5672 on the client side when the client should be connecting with port 5671.  After doing a little research this might be a feature of spring boot's rabbitmq autoconfiguration: https://github.com/spring-projects/spring-boot/issues/6401

It appears that if the properties below where explicitly configured and configuring the [addresses property was omitted](https://github.com/pivotal-cf/java-cfenv/blob/master/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/AmqpCfEnvProcessor.java#L71-L77) then proper port would be leveraged.  
```
spring.rabbitmq.host: 10.0.0.123
spring.rabbitmq.password: password
spring.rabbitmq.port: 5671
spring.rabbitmq.ssl.enabled: true
spring.rabbitmq.username: user
spring.rabbitmq.virtualHost: virtualhost
```

Tracing how RabbitProperties is leveraged via method determinePort: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L152-L158

This leverages an Address class that parses the port out of the URI: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java#L1014-L1024

However, the pivotal rabbitmq service broker does not return the port number in the port therefore it falls back to the default port 5672.  This appears to be the crux of issue https://github.com/spring-projects/spring-boot/issues/6401 which states that when the scheme is amqps the default port should be 5671 but i am not sure if that necessarily true. 

Initial gut reaction is for the AmqpCfEnvProcessor to not set the `spring.rabbitmq.addresses` property and instead opt to just set the other properties per the guidance given in the spring boot issue 6401.

**Comment by markpollack** [comment]
Hi!  Wow, thanks for such a well written description of the issue!  Indeed the spring-cloud-connector library created the `ConnectionFactory` by calling `setUri` which has the knowledge of how to handle `amqps` vs `amqp`.  In the boot case, since that type of functionality isn't there (maybe it will be one day) we should take the approach you mention.  I'll make a PR to fix this and if possible, it would be great if you could test against it.

**Comment by markpollack** [comment]
I pushed the PR that should work in your case - https://github.com/pivotal-cf/java-cfenv/pull/75

What will not work is if there are multiple `amqps` hosts specified.  In order for that to work Boot would need to improve the parsing of Addresses to take into account the different default port implied by having a `amqps` prefix.

**Comment by xyloman** [comment]
I have the same concern that you have @markpollack.  There are a few ways that I think this has been mitigated in PAS where the RMQ deployment only returns one host in the hosts string now that RMQ has moved to using BOSH DNS and likely future it will leverage a kubernetes dns provider with similar capabilities when running k8s. 

The other mitigation but I am not an expert in how the RMQ connection factory works but I believe that once you connect to one RMQ server you can discover the location of the other but I could be wrong.

**Comment by xyloman** [comment]
@markpollack gave feedback on the PR #75 and was able to validate that this appears to be working :)
