### ISSUE TITLE
CFEnv SCS failed authentication to spring cloud config service.

### ISSUE THREAD

**Issue by gm2552** [pivotal-cf/java-cfenv#77]
This is more of a question than an issue (maybe).  With version 1.1.2.RELEASE removing all of the oAuth2 client bootstrap configuration logic, what is the recommended procedure for configuring the oAuth 2 RESTTemplate for authenticating to spring cloud config?  Updating from 1.1.1.RELEASE to 1.1.2.RELEASE now results in an 401 error when access the service.

**Comment by dyroberts** [comment]
Hi @gm2552. The official spring-cloud-services client libraries are migrating to `java-cfenv`. There should be a new release out later this week that will depend on 1.1.2.RELEASE. Then you'll be able to follow the docs on connecting client apps (https://docs.pivotal.io/spring-cloud-services/3-1/common/client-dependencies.html). For now, you can continue to use the previous `java-cfenv` release.
