### ISSUE TITLE
MongoDB connection string options are lost

### ISSUE THREAD

**Issue by fbeaufume** [pivotal-cf/java-cfenv#80]
The MongoDB connection string options are key/value pairs at the end of the MongoDB URI. They are used to configure the pooling, timeouts, etc. An example is "?maxWaitTime=5000&connectTimeoutMS=3000". See https://docs.mongodb.com/manual/reference/connection-string/#connection-string-options

When I use Java CFEnv in a Spring Boot 2 application deployed to Cloud Foundry, my connection string options are all lost and default values are used instead.

Is this the expected behavior? How can I fine tune the connections?

**Comment by dyroberts** [comment]
Spoke on a call and recommended following the docs [here](https://github.com/pivotal-cf/java-cfenv#use-with-spring) to use SpEL to set the mongodb spring-boot properties
