### ISSUE TITLE
document dependencies for SCS and SSO

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/java-cfenv#83]
Please document that for SCS and respectively for SSO additional dependencies are necessary:

```
        <dependency>
            <groupId>io.pivotal.cfenv</groupId>
            <artifactId>java-cfenv-boot-pivotal-scs</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
```

```
        <dependency>
            <groupId>io.pivotal.cfenv</groupId>
            <artifactId>java-cfenv-boot-pivotal-sso</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
```

**Comment by dyroberts** [comment]
Thanks @vchrisb. For both SCS and SSO, users should follow the official docs of each respective tile for creating client applications. I'll make a note of this in the java-cfenv readme. I think any further specifics in either case would be redundant.
