### ISSUE TITLE
Provide capability for post processing service data

### ISSUE THREAD

**Issue by vpavic** [pivotal-cf/java-cfenv#84]
Our provider unfortunately tags PostgreSQL service with conflicting tags:

```
"tags": [
 "AWS",
 "RDS",
 "Aurora",
 "PostgreSQL",
 "MySQL"
],
```

This results in `CfJdbcUrlCreator` not being able resolve a uniqe database service:

```
2020-01-13T14:58:47.47+0100 [APP/PROC/WEB/0] OUT DEBUG|CustomLogEvent||i.p.c.s.b.CfDataSourceEnvironmentPostProcessor|[main] Skipping execution of CfDataSourceEnvironmentPostProcessor. No unique database service found. Found database service names [acme-rds-11, acme-rds-11]
```

Previously, with Spring Cloud Connectors, we were addressing this with a custom  [`ServiceDataPostProcessor`](https://docs.spring.io/spring-cloud/docs/2.0.7.RELEASE/api/org/springframework/cloud/cloudfoundry/ServiceDataPostProcessor.html) implementation that would deal with this scenario. See cloudfoundry/java-buildpack/issues/574.

Any chance Java CFEnv gets a similar capability? Are there maybe any alternatives to address this scenario?

**Comment by vpavic** [comment]
Any updates on this @dyroberts? Thanks.

**Comment by dyroberts** [comment]
@vpavic Sorry for the long delay. In this case, I would recommend dropping the java-cfenv-boot dependency and just use java-cfenv-jdbc directly. Instructions on that [here](https://github.com/pivotal-cf/java-cfenv#use-with-spring). You'll use SpEL to set the `spring.datasource.*` properties.
