### ISSUE TITLE
Need to bind multiple rabbitmq and/or mysql services to JVM

### ISSUE THREAD

**Issue by maximusfloydus** [pivotal-cf/java-cfenv#87]
I'm in PCF using SCS 3.1 with the following dependencies:
* io.pivotal.spring.cloud:spring-cloud-services-starter-config-client:3.1.1.RELEASE
  * io.pivotal.cfenv:java-cfenv-boot-pivotal-scs:2.1.1.RELEASE
     * io.pivotal.cfenv:java-cfenv-boot:2.1.1.RELEASE

[CfEnvironmentPostProcessor](https://github.com/pivotal-cf/java-cfenv/blob/a07fae10b8125601606dd951b87ecf761412043d/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/CfEnvironmentPostProcessor.java#L94) doesn't allow multiple Rabbitmq service instances to be bound to a single application.  

I'm looking for a way to override or disable CfEnvironmentPostProcessor for our rabbitmq and mysql bindings since we need to support multiple rabbitmq clusters and mysql instances in a single JVM.  I would be fine adding my own custom PostProcessor to handle these situations, but I haven't seen a clear example of how to override or disable what is set in the [META-INF/spring.factories]( https://github.com/pivotal-cf/java-cfenv/blob/a07fae10b8125601606dd951b87ecf761412043d/java-cfenv-boot/src/main/resources/META-INF/spring.factories#L2-L4)

Is the better option to use try spring-cloud/spring-cloud-connectors 2.x instead?  We are new to the PCF and would prefer to build upon the new models.

Any help would be much appreciated!

**Comment by dyroberts** [comment]
Hi @maximusfloydus. In this case, I would suggest excluding the `io.pivotal.cfenv:java-cfenv-boot` dependency and adding a dependency on the more flexible base library `io.pivotal.cfenv:java-cfenv-jdbc`. Once this is done, you can follow the docs [here](https://github.com/pivotal-cf/java-cfenv#use-with-spring) to connect as many services as you need of each type.

**Comment by dyroberts** [comment]
The other option is, as you mentioned, to use the 2.x line of scs starters. But, as you've noticed, they use spring-cloud-connectors; which I don't believe will reduce the complexity for you.

**Comment by maximusfloydus** [comment]
@dyroberts Will the pivotal scs client still work if I exclude `io.pivotal.cfenv:java-cfenv-boot`?  I haven't had a chance to see if it is has a runtime dependency on it.

**Comment by maximusfloydus** [comment]
By excluding `io.pivotal.cfenv:java-cfenv-boot` I lose access to two import classes: `io.pivotal.cfenv.spring.boot.CfEnvProcessor` and `io.pivotal.cfenv.spring.boot.CfEnvProcessorProperties`.  Could these two classes be moved to the java-cfenv project from java-cfenv-boot.  I currently have to recreate them in order to create new Processors.

**Comment by dyroberts** [comment]
The `CfEnvProcessor` is the main abstraction of the boot module. Since you're not going to use the boot module, you won't be writing any CfEnvProcessors! You'll just follow the docs [here](https://github.com/pivotal-cf/java-cfenv#use-with-spring) to set application properties with SpEL and the CfJdbcEnv bean. See my comment above for details on the particular properties that need setting for scs.

**Comment by dyroberts** [comment]
After some thought, I think the approach suggested above is the best one for supporting multiple services of the same type.

**Comment by maximusfloydus** [comment]
@dyroberts Can SpEL be used in Spring Cloud Configuration or only in a local properties file?   

It would be ideal if pivotal/vmware provide a little more flexibility in this library.  I really would like to use this library for SCS Config, SCS registry, SSO and maybe a few other things.  I just can't use it for JDBC or AMPQ in my current applications.  I saw a PR to support a "enabled" flag #40.  Another option would be allow the PostProcessor to not exit when it finds multiple, but just log the error and process the rest.  I could do a PR also, if there is a path you guys would be willing to accept.

**Comment by dyroberts** [comment]
Thanks for your persistence @maximusfloydus. I've merged the `Is enabled` PR and released java-cfenv v2.1.2.RELEASE.
