### ISSUE TITLE
Add support for multiple services of same type

### ISSUE THREAD

**Issue by j-musca** [pivotal-cf/java-cfenv#94]
We have a Spring Boot app which uses two RabbitMQ services when deployed in Cloud-Foundry and we wanted to migrate it to cfenv (previously we used Spring Cloud Connectors).

After the migration we get the error "No unique Rabbit service found. Found service names..." from the `CfEnvironmentPostProcessor.class`.

With Spring Cloud Connectors we could simply use a qualifier annotation to select the correct RabbitMQ service.

We would like to see this use case also supported by cfenv.

**Comment by mbwhelan** [comment]
The only way I've made it work is by disabling rabbitmq bindings: https://github.com/pivotal-cf/java-cfenv/issues/87 https://github.com/pivotal-cf/java-cfenv/issues/93 
It is not ideal.

**Comment by mbwhelan** [comment]
The issue I faced with using java-cfenv and java-cfenv-jdbc instead is my requirement to use java-cfenv-boot-pivotal-scs pulls in java-cfenv-boot, which then breaks because I have multiple RabbitMQ service bindings.

It would be nice to disable the exception if multiple service bindings exist and just let the spring.{service}.values to null.  This is how the jdbc/datasource binding works.

**Comment by joaodias14** [comment]
@dyroberts, I agree with @mbwhelan. It makes little sense to blow up the app just because there are multiple service bindings. Yes, it is true that then you can't make anything with them, but maybe the application itself does, so why aren't such multiple bindings be ignored?

**Comment by joaodias14** [comment]
Additionally, this `java-cfenv` solution feels like a step backward instead of a step forward. 
With this, code like the one below don't work while with the old spring cloud connectors with was possible:

    @Bean(VMOS_API_REDIS_SERVER_COMMANDS_NAME)
    fun reactiveVmosApiRedisServerCommands(@Qualifier(VMOS_API_REDIS_SERVICE_NAME) connectionFactory: ReactiveRedisConnectionFactory): ReactiveServerCommands {
        return connectionFactory.reactiveConnection.serverCommands()
    }

    @Bean(VMOS_IMAGES_REDIS_SERVER_COMMANDS_NAME)
    fun reactiveVmosImagesRedisServerCommands(@Qualifier(VMOS_IMAGES_REDIS_SERVICE_NAME) connectionFactory: ReactiveRedisConnectionFactory): ReactiveServerCommands {
        return connectionFactory.reactiveConnection.serverCommands()
    }
